### ISSUE TITLE
Add link to second stream 

### ISSUE THREAD

**Issue by tim-phillips** [kchungradio/kchungradio.org#28]
Probably best to add this to the first stream page and then link back to the first stream from the second page

**Comment by nikoleguzman** [comment]
Yeah thinking would be cool if the first page automatically played stream 1 (as it is now) but maybe there could be a link to stream 2 on it as well? So under the giant Play button would be: stream 1 | stream 2. Then "stream 2' could be added to the main nav bar right next to "live stream" which would then be renamed "stream 1"
